# List all source files explicitly
set(MAIN_SOURCES
    ${CMAKE_SOURCE_DIR}/src/Artist.cpp
    ${CMAKE_SOURCE_DIR}/src/ArtistParser.cpp
    ${CMAKE_SOURCE_DIR}/src/CollisionHandler.cpp
    ${CMAKE_SOURCE_DIR}/src/Controller.cpp
    ${CMAKE_SOURCE_DIR}/src/FileHandler.cpp
    ${CMAKE_SOURCE_DIR}/src/FileLoader.cpp
    ${CMAKE_SOURCE_DIR}/src/GridParser.cpp
    ${CMAKE_SOURCE_DIR}/src/IArtistParser.cpp
    ${CMAKE_SOURCE_DIR}/src/IFileLoader.cpp
    ${CMAKE_SOURCE_DIR}/src/IGridParser.cpp
    ${CMAKE_SOURCE_DIR}/src/Input.cpp
    ${CMAKE_SOURCE_DIR}/src/InputStructs.cpp
    ${CMAKE_SOURCE_DIR}/src/ITileState.cpp
    ${CMAKE_SOURCE_DIR}/src/LevelData.cpp
    ${CMAKE_SOURCE_DIR}/src/Main.cpp
    ${CMAKE_SOURCE_DIR}/src/Memento.cpp
    ${CMAKE_SOURCE_DIR}/src/MementoManager.cpp
    ${CMAKE_SOURCE_DIR}/src/Model.cpp
    ${CMAKE_SOURCE_DIR}/src/Pathfinder.cpp
    ${CMAKE_SOURCE_DIR}/src/PollingTUI.cpp
    ${CMAKE_SOURCE_DIR}/src/Quadtree.cpp
    ${CMAKE_SOURCE_DIR}/src/Renderer.cpp
    ${CMAKE_SOURCE_DIR}/src/Tile.cpp
    ${CMAKE_SOURCE_DIR}/src/TileFactory.cpp
    ${CMAKE_SOURCE_DIR}/src/TileNode.cpp
    ${CMAKE_SOURCE_DIR}/src/View.cpp
)