@startuml

class fileHandler {
    +std::vector<ParsedPerson> loadArtist(std::string aFilePath)
    +ParsedGrid loadGrid(std::string aFilePath)
}

class FileLoaderContext{
    + std::unique_ptr<std::ifstream> loadFile(const std::string& path)
}

interface FileLoader{
    virtual std::unique_ptr<std::ifstream> loadFile(const std::string& path) = 0
}

class URLFileLoader{
    std::unique_ptr<std::ifstream> loadFile(const std::string& url) override
}

class LocalFileLoader{
    std::unique_ptr<std::ifstream> loadFile(const std::string& url) override
}

class ArtistParserStrategy {
    + std::vector<ParsedPerson> parseFile(LoadedFile& aLoadedFile)
}

interface ArtistParser {
    + std::vector<ParsedPerson> parseFile(LoadedFile& aLoadedFile)
}

class ArtistCSVParser{
    + std::vector<ParsedPerson> parseFile(LoadedFile& aLoadedFile)
}

class GridParserStrategy{
    ParsedGrid parseFile(LoadedFile& aLoadedFile)
}

interface GridParser{
    ParsedGrid parseFile(LoadedFile& aLoadedFile)
}

class GridXMLParser{
    ParsedGrid parseFile(LoadedFile& aLoadedFile)
}

class GridTXTParser{
    ParsedGrid parseFile(LoadedFile& aLoadedFile)
}

' class artistParserStrategy {
'     +std::unique_ptr<ArtistParser> getParser(FileType fileType)
'     +std::vector<ParsedPerson> parseFile(LoadedFile& aLoadedFile)
' }

class controller{

}

class model{
    +void createLevel(std::vector<ParsedPerson> aPersons, ParsedGrid aGrid)
    +const levelData& getLevelData() const
    +void updateModel()
}

class levelData{
    +levelData()
    +~levelData()

    +void updateLevelData()
    +void buildLevelData(std::vector<parsedPerson> aPersons, parsedGrid aGrid)
    +void getGridColor(int tileIndex, int &red, int &green, int &blue) const
    +const std::vector<std::unique_ptr<tile>>& getGrid() const;
    +const std::vector<std::unique_ptr<artist>>& getPeople() const;

    -std::vector<std::unique_ptr<artist>> mPeople
    -std::vector<std::unique_ptr<tile>> mGrid
    -int mCols
    -int mRows
    -std::vector<gridColor> mGridColor
}

class tile{
    +tile(std::unique_ptr<iTileState> initialState)
    +~tile() = default

    +void onCollide()
    +void setState(std::unique_ptr<iTileState> newState)
    +char getColor() const

    -std::unique_ptr<iTileState> state
}

interface iTileState{
    +void onCollide(tile* t)
    +char getColor() const
    +void enter(tile* t)
    +void exit(tile* t)
}

class tileStateRed{
}

class tileStateBlue{
}

class tileStateGray{
}

class tileStateYellow{
}

class tileStateWhite{
}

class artist{
    ' +class location{
    '     float x;
    '     float y;
    ' }
    +artist(float aX, float aY, float aVelX, float aVelY)
    +void updatePerson()
    +void update()
    +location getLocation() const
    +void setLocation(location aLocation)
    +void onCollide()

    -location mLocation
    -float mVelX
    -float mVelY
}

class inputHandler{
}

class mouse{
    ' use 3rd party library to get mouse coordinates and translate to generic data
}

class keyboard{
    ' use 3rd party library to get keyboard input and translate to generic data
}

class xboxController{
    ' use 3rd party library to get xbox controller input and translate to generic data
}

class tileFactory{
    +static std::unique_ptr<tile> createTile(char color)
    -static tileColor charToTileColor(char color)
}

class view{}

class parsedArtist{
    float x;
    float y;
    float vx;
    float vy;
}

' vector<char> parsedTile()

class parsedGrid{
    int rows
    int cols
    std::vector<gridColor> colors
    std::vector<char> grid
}

class gridColor{
    +char letter
    +int red
    +int green
    +int blue
    +int weight
}

class parsedGridColor{
    char letter;
    int red;
    int green;
    int blue;
    int weight;
}


controller <-- fileHandler
controller <-- model
controller <-- inputHandler
controller <-- view
view <-- model

' model
model <-- levelData
levelData <-- tile
tile <-- iTileState
iTileState <|.. tileStateRed
iTileState <|.. tileStateBlue
iTileState <|.. tileStateGray
iTileState <|.. tileStateYellow
iTileState <|.. tileStateWhite

levelData <-- artist

levelData <-- tileFactory

' filehandler
fileHandler <-- FileLoaderContext
FileLoaderContext <-- FileLoader
FileLoader <|.. URLFileLoader
FileLoader <|.. LocalFileLoader

' Parser
fileHandler <-- ArtistParserStrategy
fileHandler <-- GridParserStrategy

ArtistParserStrategy <-- ArtistParser
ArtistParser <|.. ArtistCSVParser

GridParserStrategy <-- GridParser
GridParser <|.. GridTXTParser
GridParser <|.. GridXMLParser


' inputHandler
inputHandler <-- mouse
inputHandler <-- keyboard
inputHandler <-- xboxController

@enduml
